#!/bin/bash
sudo pkill -u "$whoami" > /dev/null 2>&1
sudo rm -r /home/"$whoami" > /dev/null 2>&1
sudo deluser -rf "$whoami" > /dev/null 2>&1
#response=0

#for a in $(who | awk '{ print $1 }')
#do
#	if [[ "$a" == "$(whoami)" ]]; then
#		echo "skipping current user..."
#	else
#		while [[ $response == '0' ]]; do
#			printf "You want to delete logged in user [$a]? (y/n) "
#			read varname
#			if [[ "$varname" == "y" ]]; then
#				printf "deleting user [$a]\n"
#				sudo pkill -u "$a" && sudo deluser --remove-home -rf "$a"
#				((response++))
#			elif [[ "$varname" == "n" ]]; then
#				printf "skipping [$a]\n"
#				((response++))
#			else
#				echo "input 'y' or 'n'"
#			fi
#		done
#		((response=0))
#	fi
#done
