#!/bin/bash
response=1

for a in $(who | awk '{ print $1 }')
do
	if [[ "$a" == "$(whoami)" ]]; then
		if [[ $response == '1' ]]; then
			echo "skipping current user..."
			((response=0))
		fi
	else
		((response=0))
		while [[ $response == '0' ]]; do
			printf "You want to delete logged in user [$a]? (y/n) "
			read varname
			if [[ "$varname" == "y" ]]; then
				printf "deleting user [$a]\n"
				sudo pkill -u "$a"
				sudo userdel -rf "$a" > /dev/null 2>&1
				((response++))
			elif [[ "$varname" == "n" ]]; then
				printf "skipping [$a]\n"
				((response++))
			else
				echo "input 'y' or 'n'"
			fi
		done
	fi
done
