#!/bin/bash
#user="$(whoami)"

#lock user account
#passwd -l "$user"

#kill running processes
#pgrep -u "$user"
#ps -fp $(pgrep -u "$user")
#killall -KILL -u "$user"

#delete at jobs and remove cron jobs
#find /var/spool/at/ -name "[^.}*" -type f -user "$user" -delete
#crontab -r -u "$user"

#delete print jobs
#lprm "$user"

#delete account
#userdel -r "$user"

#sudo killall -u "$user"
#echo "after killall"
#sudo userdel -rf "$user"
#echo "after deluser"
#rm -r /home/"$user"

response=0

for a in $(who | awk '{ print $1 }')
do
	if [[ "$a" == "$(whoami)" ]]; then
		echo "skipping current user..."
	else
		while [[ $response == '0' ]]; do
			printf "You want to delete logged in user [$a]? (y/n) "
			read varname
			if [[ "$varname" == "y" ]]; then
				printf "deleting user [$a]\n"
				sudo pkill -u "$a"
				sudo userdel -rf "$a"
				rm -r /home/"$a"
				((response++))
			elif [[ "$varname" == "n" ]]; then
				printf "skipping [$a]\n"
				((response++))
			else
				echo "input 'y' or 'n'"
			fi
		done
		((response=0))
	fi
done
