#!/bin/bash

echo -n "Enter network interface: "
read name

networkinterface=$name
networkinterface_check=$( ifconfig -l )
ether=$( ifconfig $networkinterface | grep ether | awk '{ print $2 }' )
inet=$( ifconfig $networkinterface | grep inet | awk '{ print $2 }' )
j=0

if [[ $networkinterface_check == $name ]]; then
	echo "error: $name is nonvalid network interface"
	exit 0
fi
for b in ${ether}; do
	((j=0))
	for c in ${inet}; do
		if [[ $c =~ [':'] ]]; then
			((j++))
		else
			echo "NIC : ether		: inet"
			echo "$networkinterface : $b : $c"
			break
		fi
	done
	break
	((j++))
done

exit 0